In [1]:
import tensorflow as tf

In [3]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7])

In [4]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [6]:
for ele in dataset:
    print(ele, ele.numpy())

tf.Tensor(1, shape=(), dtype=int32) 1
tf.Tensor(2, shape=(), dtype=int32) 2
tf.Tensor(3, shape=(), dtype=int32) 3
tf.Tensor(4, shape=(), dtype=int32) 4
tf.Tensor(5, shape=(), dtype=int32) 5
tf.Tensor(6, shape=(), dtype=int32) 6
tf.Tensor(7, shape=(), dtype=int32) 7


In [9]:
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5,6]])

In [10]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [11]:
for ele in dataset:
    print(ele, ele.numpy())

tf.Tensor([1 2], shape=(2,), dtype=int32) [1 2]
tf.Tensor([3 4], shape=(2,), dtype=int32) [3 4]
tf.Tensor([5 6], shape=(2,), dtype=int32) [5 6]


In [12]:
dataset_dict = tf.data.Dataset.from_tensor_slices({
    'a':[1,2,3,4],'b':[1,4,5,7],'c':[23,45,6,7]
})

In [13]:
dataset_dict

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [14]:
for ele in dataset.take(1): #take
    print(ele, ele.numpy())

tf.Tensor([1 2], shape=(2,), dtype=int32) [1 2]


In [15]:
next(iter(dataset.take(1)))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [17]:
dataset = dataset.shuffle(3) #乱序
dataset = dataset.repeat(6)


<RepeatDataset shapes: (2,), types: tf.int32>

In [18]:
for ele in dataset: #take
    print(ele, ele.numpy())

tf.Tensor([5 6], shape=(2,), dtype=int32) [5 6]
tf.Tensor([3 4], shape=(2,), dtype=int32) [3 4]
tf.Tensor([1 2], shape=(2,), dtype=int32) [1 2]
tf.Tensor([5 6], shape=(2,), dtype=int32) [5 6]
tf.Tensor([3 4], shape=(2,), dtype=int32) [3 4]
tf.Tensor([1 2], shape=(2,), dtype=int32) [1 2]
tf.Tensor([3 4], shape=(2,), dtype=int32) [3 4]
tf.Tensor([1 2], shape=(2,), dtype=int32) [1 2]
tf.Tensor([5 6], shape=(2,), dtype=int32) [5 6]
tf.Tensor([5 6], shape=(2,), dtype=int32) [5 6]
tf.Tensor([3 4], shape=(2,), dtype=int32) [3 4]
tf.Tensor([1 2], shape=(2,), dtype=int32) [1 2]
tf.Tensor([1 2], shape=(2,), dtype=int32) [1 2]
tf.Tensor([3 4], shape=(2,), dtype=int32) [3 4]
tf.Tensor([5 6], shape=(2,), dtype=int32) [5 6]
tf.Tensor([5 6], shape=(2,), dtype=int32) [5 6]
tf.Tensor([3 4], shape=(2,), dtype=int32) [3 4]
tf.Tensor([1 2], shape=(2,), dtype=int32) [1 2]


In [19]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7])

In [20]:
dataset = dataset.map(tf.square)

In [21]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49


In [23]:
(train_image, train_label),(test_image, test_label) = tf.keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [24]:
train_image = train_image /255
test_image = test_image /255

In [27]:
ds_train_img = tf.data.Dataset.from_tensor_slices(train_image )

In [47]:
ds_test = tf.data.Dataset.from_tensor_slices((test_image,test_label) )

In [50]:
ds_test= ds_test.batch(64)

In [28]:
ds_train_img

<TensorSliceDataset shapes: (28, 28), types: tf.float64>

In [29]:
ds_train_label = tf.data.Dataset.from_tensor_slices(train_label )

In [30]:
ds_train_label

<TensorSliceDataset shapes: (), types: tf.uint8>

In [32]:
ds_train = tf.data.Dataset.zip((ds_train_img , ds_train_label))

In [33]:
ds_train

<ZipDataset shapes: ((28, 28), ()), types: (tf.float64, tf.uint8)>

In [34]:
ds_train = ds_train.shuffle(10000).repeat().batch(64)

In [42]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10,activation='softmax'),
])

In [43]:
model.compile(optimizer = 'adam',
             loss='sparse_categorical_crossentropy',
             metrics=['acc'])

In [44]:
steps_per_epochs = train_image.shape[0] / 64

In [46]:
model.fit(ds_train, 
          epochs=5,
          steps_per_epoch=steps_per_epochs,
          validation_data=ds_test,
          validation_steps=10000/64)

Epoch 1/5
938/937 [==============================] - 2s 2ms/step - loss: 0.3008 - acc: 0.9154
Epoch 2/5
938/937 [==============================] - 1s 2ms/step - loss: 0.1380 - acc: 0.9600
Epoch 3/5
938/937 [==============================] - 1s 2ms/step - loss: 0.0964 - acc: 0.9718
Epoch 4/5
938/937 [==============================] - 1s 2ms/step - loss: 0.0723 - acc: 0.9794
Epoch 5/5
938/937 [==============================] - 1s 2ms/step - loss: 0.0562 - acc: 0.9835
