In [1]:
import tensorflow as tf

In [2]:
print('tf{}'.format(tf.__version__))

tf2.8.0


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
(train_image, train_label),(test_image, test_label) = tf.keras.datasets.fashion_mnist.load_data()

In [5]:
train_image.shape,train_label.shape,test_image.shape,test_label.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [7]:
train_image = train_image/255
test_image = test_image/255

In [8]:
train_label

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [21]:
train_label_onehot = tf.keras.utils.to_categorical(train_label)
test_label_onehot = tf.keras.utils.to_categorical(test_label)

In [13]:
train_label_onehot[0],test_label_onehot

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))

In [17]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax')) # output10

In [22]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy', # diff
              metrics=['acc']
)

In [23]:
model.fit(train_image,train_label_onehot,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.0890 - acc: 0.6629
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.6416 - acc: 0.7686
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5674 - acc: 0.7965
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5239 - acc: 0.8134
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4965 - acc: 0.8244


predict = model.predict(test_image)

In [24]:
predict = model.predict(test_image)

In [25]:
predict.shape

(10000, 10)

In [26]:
predict[0]

array([1.6290916e-06, 1.0128537e-07, 9.4969582e-06, 1.4291090e-05,
       1.9133260e-05, 1.2500043e-01, 1.6075568e-05, 3.9713517e-01,
       4.4250926e-03, 4.7337851e-01], dtype=float32)

In [27]:
np.argmax(predict[0])

9